services:
  backend:
    build: .
    working_dir: /app/backend
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
    
  adapter:
    image: node:22
    working_dir: /app
    command: sh -c "npm install && node src/adapter/adapter.js"
    volumes:
      - ./frontend:/app
    environment:
      - GAME_SERVER_HOST=backend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    image: node:22
    working_dir: /app
    command: sh -c "npm run dev"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_ADAPTER_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - adapter
    restart: unless-stopped
