version: '3'

services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/backend/data
    
  adapter:
    image: node:18
    working_dir: /app
    command: node adapter.js
    volumes:
      - ./frontend/src/adapter:/app
    environment:
      - GAME_SERVER_HOST=backend
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_ADAPTER_URL=http://adapter:3001
    ports:
      - "3000:3000"
    depends_on:
      - adapter
    restart: unless-stopped
